name: parchi_student_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0 # Adjusted to ensure compatibility

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management (Runtime)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking & storage
  go_router: ^13.0.0
  qr_flutter: ^4.1.0
  image_picker: ^1.0.7
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation (Required for Riverpod)
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - .env