name: parchi_student_app
description: "A student discount app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0 # Adjusted to ensure compatibility

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management (Runtime)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking & storage
  go_router: ^13.0.0
  qr_flutter: ^4.1.0
  image_picker: ^1.0.7
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.3
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation (Required for Riverpod)
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  custom_refresh_indicator: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/parchi-icon.png
    - assets/ParchiFullText.svg
    - assets/parchi-icon.svg
    - assets/Parchi-Icon-with-new-blue.png
    - assets/ParchiFullTextYellow.svg 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Parchi-Icon-with-old-blue.png"